---
kind: pipeline
type: docker
name: default

services:
  - name: vault
    image: vault:1.5.3
    ports:
      - 8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "changeme"

steps:
  - name: Wait for services
    image: jwilder/dockerize
    pull: if-not-exists
    commands:
      - dockerize -wait tcp://vault:8200 -timeout 1m
  
  - name: Enable Vault Transit
    image: vault:1.5.3
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "changeme"
    commands:
      - vault secrets enable transit

  - name: Test & vet
    image: golang:1.18
    environment:
      GO111MODULE: on
      KAIGARA_VAULT_ADDR: "http://vault:8200"
      KAIGARA_VAULT_TOKEN: "changeme"
    commands:
      - ./run_tests.sh

trigger:
  event: [ push ]
