---
kind: pipeline
type: docker
name: default

steps:
  - name: Test & vet
    image: golang:1.17
    environment:
      GO111MODULE: on
    commands:
      - ./run_tests.sh

trigger:
  event: [ push ]
